services:
  postgres:
    container_name: postgres-morpheus
    image: "postgres:15"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=9HQXvYP$&*
      - POSTGRES_DB=postgres
    volumes:
      - postgres-volume:/var/lib/postgresql/data
      - /usr/local/bin/docker-entrypoint.sh:/docker-entrypoint.sh
    restart: always
volumes:
  postgres-volume:
    driver: local